# Generated by Django 6.0.2 on 2026-02-09 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='procedure',
            options={'verbose_name': 'Procedimento', 'verbose_name_plural': 'Procedimentos'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(verbose_name='Data e Horário'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.procedure', verbose_name='Procedimento'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do Procedimento'),
        ),
    ]
