# Generated by Django 6.0.2 on 2026-02-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_alter_procedure_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Agendado'), ('CANCELED', 'Cancelado')], default='SCHEDULED', max_length=20),
        ),
    ]
