# Generated by Django 6.0.2 on 2026-02-12 22:53

import appointments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_appointment_is_confirmed_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[appointments.models.validate_cpf]),
        ),
    ]
