# Generated by Django 6.0.2 on 2026-02-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_patient_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Agendado'), ('CANCELED', 'Cancelado'), ('DONE', 'Concluído'), ('NO_SHOW', 'Não compareceu')], default='SCHEDULED', max_length=20),
        ),
    ]
